### ISSUE TITLE
Separate transactions with the same asset and amount generate the same hash

### ISSUE THREAD

**Issue by glenn-chen** [ResilientEcosystem/sdk#14]
Timestamp should be added as an input to the hash for creating transaction ids

**Comment by royari** [comment]
I think this is by design. So that duplicates of the same asset does not exist on the chain.

**Comment by glenn-chen** [comment]
You're right, this came up when users tried to add more of the same asset into circulation, but it seems that the amount of an asset does not ever change from what's specified in the first CREATE transaction. Closing the issue now.
